[package]
name = "binance_spot_tests"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[lints]
workspace = true


[lib]
path = "src/fake_lib.rs"


# For testing
[dev-dependencies]
client_error_ext = { workspace = true }
common_exchange = { workspace = true }
common_ims = { workspace = true }
config_manager = { workspace = true }
ims_data_client = { workspace = true }
iggy_test_utils = { workspace = true }
# External crates
service_utils = { workspace = true }
tokio = { workspace = true }