[package]
name = "message_consumer"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[dependencies]
# Internal crates
message_shared = {workspace = true}
trait_event_consumer = { workspace = true }

# External crates
futures-util = { workspace = true }
iggy = {workspace = true}
tokio = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true