[package]
name = "message_stream"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[dependencies]
# Internal crates
message_producer = {workspace = true}
message_shared = {workspace = true}
# External crates
iggy = {workspace = true}

[lints]
workspace = true
