[workspace]
resolver = "2"

members = [
    "queng_common/*",
]

[workspace.package]
edition = "2021"
rust-version = "1.82.0"
readme = "README.md"
repository = "https://github.com/marvin-hansen/cgp-exploration"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>"]

# Linting with clippy
[workspace.lints.clippy]
all = "warn"

# Linting strict mode
[workspace.lints.rust]
# Warnings
deprecated-safe = "warn"
deprecated_safe_2024 = "warn"

# Optimize all crates
[profile.release]
opt-level = 3
strip = true  # Automatically strip debug symbols from the binary
lto = true    # Enable Link Time Optimization (LTO)
codegen-units = 1 # Reduce Parallel Code Generation Units to Increase Optimization

# There's a Cargo feature named profile-overrides
# that lets you override the optimization level of dependencies.
# https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html
[profile.release.package."*"]
opt-level = 3
strip = 'debuginfo'  # Automatically strip debug infos from the binary to reduce size
codegen-units = 1 # Reduce Parallel Code Generation Units to Increase Optimization

[workspace.dependencies]
# ==============
# Internal Aliases
# ==============

# Common
common_errors = { path = "queng_common/common_errors" }

# ==============
# External crates
# ==============
# Dependencies for macros
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
# Regular dependencies
chrono = { version = "0.4.38", features = ["serde"] }
rust_decimal = { version = "1.36" }

