[package]
name = "trait_data_integration"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[lints]
workspace = true


[dependencies]
# Internal crates
common_data_bar = {workspace = true}
common_errors = {workspace = true}
# External crates
trait-variant  = {workspace = true}
