[package]
name = "message_client_builder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true


[[example]]
name = "basic_message_client_builder"
path = "examples/main.rs"


[lints]
workspace = true


[dependencies]
# Internal crates
message_consumer = { workspace = true }
message_producer = { workspace = true }
message_shared = { workspace = true }
trait_event_consumer = { workspace = true }
# External crates
iggy = { workspace = true }

# For testing
[dev-dependencies]
# Internal crates
config_manager = { workspace = true }
iggy_test_utils = { workspace = true }
# External crates
service_utils = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
