[package]
name = "sbe_messages_client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true


[lints]
workspace = true


[dependencies]
sbe_bindings = { workspace = true }
sbe_types  = { workspace = true }