[package]
name = "ims_data_client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true


[[example]]
name = "basic_ims_data_client"
path = "examples/main.rs"


[dependencies]
# Internal crates
common_data_bar = { workspace = true }
common_exchange = { workspace = true }
common_ims = { workspace = true }
message_consumer = { workspace = true }
message_producer = { workspace = true }
message_shared = { workspace = true }
sbe_messages_control = { workspace = true }
sbe_messages_client = { workspace = true }
sbe_types = { workspace = true }
trait_event_consumer = { workspace = true }
trait_event_processor = { workspace = true }
# External crates
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
iggy = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[lints]
workspace = true
