[package]
name = "iggy_producer_ext"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true


[lints]
workspace = true


[dependencies]
# External crates
bytes = { workspace = true }
iggy = { workspace = true }
trait-variant = { workspace = true }